USE [master]
GO
/****** Object:  Database [Desafio]    Script Date: 24/01/2022 18:05:30 ******/
CREATE DATABASE [Desafio]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Desafio', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\Desafio.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Desafio_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\Desafio_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [Desafio] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin --tarefa 1
EXEC [Desafio].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Desafio] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Desafio] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Desafio] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Desafio] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Desafio] SET ARITHABORT OFF 
GO
ALTER DATABASE [Desafio] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Desafio] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Desafio] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Desafio] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Desafio] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Desafio] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Desafio] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Desafio] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Desafio] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Desafio] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Desafio] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Desafio] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Desafio] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Desafio] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Desafio] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Desafio] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Desafio] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Desafio] SET RECOVERY FULL 
GO
ALTER DATABASE [Desafio] SET  MULTI_USER 
GO
ALTER DATABASE [Desafio] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Desafio] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Desafio] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Desafio] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [Desafio] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'Desafio', N'ON'
GO
USE [Desafio]
GO
/****** Object:  Table [dbo].[Categoria]    Script Date: 24/01/2022 18:05:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Categoria](
	[id_categoria] [int] IDENTITY(1,1) NOT NULL,
	[nome] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Categoria] PRIMARY KEY CLUSTERED 
(
	[id_categoria] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Lancamento]    Script Date: 24/01/2022 18:05:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Lancamento](
	[id_lancamento] [int] IDENTITY(1,1) NOT NULL,
	[valor] [decimal](18, 2) NOT NULL,
	[data] [datetime] NOT NULL,
	[id_subcategoria] [int] NOT NULL,
	[comentario] [nvarchar](50) NULL,
 CONSTRAINT [PK_Lancamento] PRIMARY KEY CLUSTERED 
(
	[id_lancamento] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Subcategoria]    Script Date: 24/01/2022 18:05:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Subcategoria](
	[id_subcategoria] [int] IDENTITY(1,1) NOT NULL,
	[nome] [nvarchar](50) NOT NULL,
	[id_categoria] [int] NOT NULL,
 CONSTRAINT [PK_Subcategoria] PRIMARY KEY CLUSTERED 
(
	[id_subcategoria] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[Lancamento]  WITH CHECK ADD  CONSTRAINT [FK_Lancamento_Subcategoria] FOREIGN KEY([id_subcategoria])
REFERENCES [dbo].[Subcategoria] ([id_subcategoria])
GO
ALTER TABLE [dbo].[Lancamento] CHECK CONSTRAINT [FK_Lancamento_Subcategoria]
GO
ALTER TABLE [dbo].[Subcategoria]  WITH CHECK ADD  CONSTRAINT [FK_Subcategoria_Categoria] FOREIGN KEY([id_categoria])
REFERENCES [dbo].[Categoria] ([id_categoria])
GO
ALTER TABLE [dbo].[Subcategoria] CHECK CONSTRAINT [FK_Subcategoria_Categoria]
GO
USE [master]
GO
ALTER DATABASE [Desafio] SET  READ_WRITE 
GO
